//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinclair_cis2222_spring2020 {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Lab02;
		
		protected System.Web.UI.HtmlControls.HtmlForm form2;
		
		protected System.Web.UI.WebControls.Label LoanAmoutLabel;
		
		protected System.Web.UI.WebControls.TextBox LoanAmountInput;
		
		protected System.Web.UI.WebControls.Label InterestRateLabel;
		
		protected System.Web.UI.WebControls.RadioButtonList InterestRateInput;
		
		protected System.Web.UI.WebControls.Label LoanTermLabel;
		
		protected System.Web.UI.WebControls.DropDownList TermInput;
		
		protected System.Web.UI.WebControls.Button CalcSubmit;
		
		protected System.Web.UI.WebControls.Button CalcClear;
		
		protected System.Web.UI.WebControls.Label MortgageLabel;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Lab01;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label UserNameLabel;
		
		protected System.Web.UI.WebControls.TextBox UserNameTextBox;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator reqName;
		
		protected System.Web.UI.WebControls.Label UserEmailLabel;
		
		protected System.Web.UI.WebControls.TextBox UserEmailTextBox;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator reqEmail;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator regExEmail;
		
		protected System.Web.UI.WebControls.Label UserPhoneLabel;
		
		protected System.Web.UI.WebControls.TextBox UserPhoneTextBox;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator reqPhone;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator regExPhone;
		
		protected System.Web.UI.WebControls.Button UserSubmit;
		
		protected System.Web.UI.WebControls.Button UserClear;
		
		protected System.Web.UI.WebControls.Label MessageLabel;
	}
}
